# Generated by Django 3.2.3 on 2021-05-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producty',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_fr', models.CharField(max_length=200)),
                ('brands', models.CharField(max_length=200)),
                ('nutriscore_grade', models.CharField(max_length=1)),
                ('stores', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
