# Generated by Django 3.2.3 on 2021-05-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210527_0915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producty',
            new_name='Product',
        ),
    ]
