# Generated by Django 4.0.1 on 2022-01-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='unlikes',
        ),
    ]
